site_name: Guide | Summer 2021 of Open Source Promotion Plan
site_dir: public
repo_url: https://summer.iscas.ac.cn/help/
repo_name: 中文版

copyright: Copyright &copy; 2020 - 2021 Organizing Committee, Summer 2021 of Open Source Promotion Plan

theme:
  name: material
  language: 'en'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/solid/link
  logo: assets/logo.svg
  favicon: assets/favicon.jpg

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:summer@iscas.ac.cn

extra_javascript:
    - 'js/tongji.js'

plugins:
  - git-revision-date
  - search

nav:
  - Frequently Asked: index.md
  - Roles: roles.md
  - Timeline: timeline.md
  - Student Guide:
    - Questions: student.md
    - Suggestions: proj_apply.md
  - Community: community.md
  - Mentor: mentor.md
  - Cooperation: cooperation.md
  - Contact Us: contactus.md
  - Acknowledgements: acknowledgements.md
